# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_blog', '0003_auto_20180413_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='media/%y/%m/%d', verbose_name='图片'),
        ),
    ]
