# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_blog', '0006_auto_20180414_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content_1',
            field=models.TextField(default=True, null=True, verbose_name='博客内容：第一段'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.TextField(default=True, null=True, verbose_name='博客内容：第二段'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle_title',
            field=models.CharField(default=True, max_length=100, verbose_name='single里的副标题'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='blog/single通用界面图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='博客主标题'),
        ),
    ]
