# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_blog', '0007_auto_20180419_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle_title',
            field=models.CharField(max_length=100, verbose_name='single里的副标题'),
        ),
    ]
