# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_blog', '0008_auto_20180419_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_1',
            field=models.TextField(null=True, verbose_name='博客内容：第一段'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_2',
            field=models.TextField(null=True, verbose_name='博客内容：第二段'),
        ),
    ]
