# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_blog', '0009_auto_20180419_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_1',
            field=models.TextField(default=True, null=True, verbose_name='博客内容：第一段'),
        ),
    ]
