# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_blog', '0011_auto_20180419_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
